services:
  # Local PDS for dev environment
  dev-pds:
    container_name: gander-pds-dev
    ports:
      - '2583:3000'
    environment:
      - NODE_ENV=development
      - PDS_HOSTNAME=localhost:2583
      - PDS_PORT=3000
      - PDS_SERVICE_DID=did:web:pds.gndr.local
      - PDS_ADMIN_PASSWORD=admin
      - PDS_JWT_SECRET=dev-jwt-secret
      - PDS_DATA_DIRECTORY=/pds
      - PDS_BLOBSTORE_DISK_LOCATION=/pds/blocks
      - PDS_DID_PLC_URL=http://localhost:2582
      - PDS_DATABASE_URL=postgres://pds:pds@localhost:5434/pds_dev
      - LOG_ENABLED=true
      - LOG_LEVEL=debug
      - RUN_MIGRATIONS=true
    volumes:
      - ../../packages/pds/src:/app/packages/pds/src:ro
    networks:
      - gander-dev

  # Local Gndr (AppView) for dev
  dev-gndr:
    container_name: gander-gndr-dev
    ports:
      - '2585:2585'
    environment:
      - NODE_ENV=development
      - GNDR_PORT=2585
      - GNDR_HOSTNAME=localhost:2585
      - GNDR_SERVICE_DID=did:web:gndr.local
      - GNDR_DATABASE_URL=postgres://gndr:gndr@localhost:5435/gndr_dev
      - GNDR_DID_PLC_URL=http://localhost:2582
      - GNDR_REDIS_HOST=localhost
      - GNDR_REDIS_PORT=6379
      - LOG_LEVEL=debug
      - RUN_MIGRATIONS=true
    volumes:
      - ../../packages/gndr/src:/app/packages/gndr/src:ro
    networks:
      - gander-dev

  # Local PLC for dev environment
  dev-plc:
    container_name: gander-plc-dev
    ports:
      - '2582:2582'
    environment:
      - DATABASE_URL=postgres://plc:plc@localhost:5433/plc_dev
      - ENABLE_MIGRATIONS=true
      - PORT=2582
      - LOG_LEVEL=debug
      - NODE_ENV=development
    networks:
      - gander-dev

networks:
  gander-dev:
    external:
      name: gander-hybrid-network
