// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts,import_extension="
// @generated from file gndr.proto (package gndr, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  ClearActorMutelistSubscriptionsRequest,
  ClearActorMutelistSubscriptionsResponse,
  ClearActorMutesRequest,
  ClearActorMutesResponse,
  ClearThreadMutesRequest,
  ClearThreadMutesResponse,
  CreateActorMutelistSubscriptionRequest,
  CreateActorMutelistSubscriptionResponse,
  CreateActorMuteRequest,
  CreateActorMuteResponse,
  CreateThreadMuteRequest,
  CreateThreadMuteResponse,
  DeleteActorMutelistSubscriptionRequest,
  DeleteActorMutelistSubscriptionResponse,
  DeleteActorMuteRequest,
  DeleteActorMuteResponse,
  DeleteThreadMuteRequest,
  DeleteThreadMuteResponse,
  GetActivitySubscriptionDidsRequest,
  GetActivitySubscriptionDidsResponse,
  GetActivitySubscriptionsByActorAndSubjectsRequest,
  GetActivitySubscriptionsByActorAndSubjectsResponse,
  GetActorChatDeclarationRecordsRequest,
  GetActorChatDeclarationRecordsResponse,
  GetActorFeedsRequest,
  GetActorFeedsResponse,
  GetActorFollowsActorsRequest,
  GetActorFollowsActorsResponse,
  GetActorLikesRequest,
  GetActorLikesResponse,
  GetActorListsRequest,
  GetActorListsResponse,
  GetActorMutesActorRequest,
  GetActorMutesActorResponse,
  GetActorMutesActorViaListRequest,
  GetActorMutesActorViaListResponse,
  GetActorRepostsRequest,
  GetActorRepostsResponse,
  GetActorsRequest,
  GetActorsResponse,
  GetActorStarterPacksRequest,
  GetActorStarterPacksResponse,
  GetActorTakedownRequest,
  GetActorTakedownResponse,
  GetAllLabelersRequest,
  GetAllLabelersResponse,
  GetAuthorFeedRequest,
  GetAuthorFeedResponse,
  GetBidirectionalBlockRequest,
  GetBidirectionalBlockResponse,
  GetBidirectionalBlockViaListRequest,
  GetBidirectionalBlockViaListResponse,
  GetBlobTakedownRequest,
  GetBlobTakedownResponse,
  GetBlockExistenceRequest,
  GetBlockExistenceResponse,
  GetBlocklistSubscriptionRequest,
  GetBlocklistSubscriptionResponse,
  GetBlocklistSubscriptionsRequest,
  GetBlocklistSubscriptionsResponse,
  GetBlockRecordsRequest,
  GetBlockRecordsResponse,
  GetBlocksRequest,
  GetBlocksResponse,
  GetCountsForUsersRequest,
  GetCountsForUsersResponse,
  GetDidsByHandlesRequest,
  GetDidsByHandlesResponse,
  GetFeedGeneratorRecordsRequest,
  GetFeedGeneratorRecordsResponse,
  GetFeedGeneratorStatusRequest,
  GetFeedGeneratorStatusResponse,
  GetFollowersRequest,
  GetFollowersResponse,
  GetFollowRecordsRequest,
  GetFollowRecordsResponse,
  GetFollowsFollowingRequest,
  GetFollowsFollowingResponse,
  GetFollowsRequest,
  GetFollowsResponse,
  GetFollowSuggestionsRequest,
  GetFollowSuggestionsResponse,
  GetIdentityByDidRequest,
  GetIdentityByDidResponse,
  GetIdentityByHandleRequest,
  GetIdentityByHandleResponse,
  GetInteractionCountsRequest,
  GetInteractionCountsResponse,
  GetLabelerRecordsRequest,
  GetLabelerRecordsResponse,
  GetLabelsRequest,
  GetLabelsResponse,
  GetLatestRevRequest,
  GetLatestRevResponse,
  GetLikeRecordsRequest,
  GetLikeRecordsResponse,
  GetLikesByActorAndSubjectsRequest,
  GetLikesByActorAndSubjectsResponse,
  GetLikesBySubjectRequest,
  GetLikesBySubjectResponse,
  GetLikesBySubjectSortedRequest,
  GetLikesBySubjectSortedResponse,
  GetListBlockRecordsRequest,
  GetListBlockRecordsResponse,
  GetListCountRequest,
  GetListCountResponse,
  GetListCountsRequest,
  GetListCountsResponse,
  GetListFeedRequest,
  GetListFeedResponse,
  GetListItemRecordsRequest,
  GetListItemRecordsResponse,
  GetListMembershipRequest,
  GetListMembershipResponse,
  GetListMembersRequest,
  GetListMembersResponse,
  GetListRecordsRequest,
  GetListRecordsResponse,
  GetMutelistSubscriptionRequest,
  GetMutelistSubscriptionResponse,
  GetMutelistSubscriptionsRequest,
  GetMutelistSubscriptionsResponse,
  GetMutesRequest,
  GetMutesResponse,
  GetNewUserCountForRangeRequest,
  GetNewUserCountForRangeResponse,
  GetNotificationDeclarationRecordsRequest,
  GetNotificationDeclarationRecordsResponse,
  GetNotificationPreferencesRequest,
  GetNotificationPreferencesResponse,
  GetNotificationSeenRequest,
  GetNotificationSeenResponse,
  GetNotificationsRequest,
  GetNotificationsResponse,
  GetPostgateRecordsRequest,
  GetPostgateRecordsResponse,
  GetPostRecordsRequest,
  GetPostRecordsResponse,
  GetProfileRecordsRequest,
  GetProfileRecordsResponse,
  GetQuotesBySubjectSortedRequest,
  GetQuotesBySubjectSortedResponse,
  GetRecordTakedownRequest,
  GetRecordTakedownResponse,
  GetRelationshipsRequest,
  GetRelationshipsResponse,
  GetRepostRecordsRequest,
  GetRepostRecordsResponse,
  GetRepostsByActorAndSubjectsRequest,
  GetRepostsByActorAndSubjectsResponse,
  GetRepostsBySubjectRequest,
  GetRepostsBySubjectResponse,
  GetStarterPackCountsRequest,
  GetStarterPackCountsResponse,
  GetStarterPackRecordsRequest,
  GetStarterPackRecordsResponse,
  GetStatusRecordsRequest,
  GetStatusRecordsResponse,
  GetSuggestedEntitiesRequest,
  GetSuggestedEntitiesResponse,
  GetSuggestedFeedsRequest,
  GetSuggestedFeedsResponse,
  GetThreadGateRecordsRequest,
  GetThreadGateRecordsResponse,
  GetThreadMutesOnSubjectsRequest,
  GetThreadMutesOnSubjectsResponse,
  GetThreadRequest,
  GetThreadResponse,
  GetTimelineRequest,
  GetTimelineResponse,
  GetUnreadNotificationCountRequest,
  GetUnreadNotificationCountResponse,
  GetVerificationRecordsRequest,
  GetVerificationRecordsResponse,
  GetVerificationsIssuedRequest,
  GetVerificationsIssuedResponse,
  GetVerificationsReceivedRequest,
  GetVerificationsReceivedResponse,
  PingRequest,
  PingResponse,
  SearchActorsRequest,
  SearchActorsResponse,
  SearchFeedGeneratorsRequest,
  SearchFeedGeneratorsResponse,
  SearchPostsRequest,
  SearchPostsResponse,
  SearchStarterPacksRequest,
  SearchStarterPacksResponse,
  TakedownActorRequest,
  TakedownActorResponse,
  TakedownBlobRequest,
  TakedownBlobResponse,
  TakedownRecordRequest,
  TakedownRecordResponse,
  UntakedownActorRequest,
  UntakedownActorResponse,
  UntakedownBlobRequest,
  UntakedownBlobResponse,
  UntakedownRecordRequest,
  UntakedownRecordResponse,
  UpdateActorUpstreamStatusRequest,
  UpdateActorUpstreamStatusResponse,
  UpdateNotificationSeenRequest,
  UpdateNotificationSeenResponse,
} from './gndr_pb'
import { MethodKind } from '@bufbuild/protobuf'

/**
 *
 * Read Path
 *
 *
 * @generated from service gndr.Service
 */
export const Service = {
  typeName: 'gndr.Service',
  methods: {
    /**
     * Records
     *
     * @generated from rpc gndr.Service.GetBlockRecords
     */
    getBlockRecords: {
      name: 'GetBlockRecords',
      I: GetBlockRecordsRequest,
      O: GetBlockRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetFeedGeneratorRecords
     */
    getFeedGeneratorRecords: {
      name: 'GetFeedGeneratorRecords',
      I: GetFeedGeneratorRecordsRequest,
      O: GetFeedGeneratorRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetFollowRecords
     */
    getFollowRecords: {
      name: 'GetFollowRecords',
      I: GetFollowRecordsRequest,
      O: GetFollowRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetLikeRecords
     */
    getLikeRecords: {
      name: 'GetLikeRecords',
      I: GetLikeRecordsRequest,
      O: GetLikeRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetListBlockRecords
     */
    getListBlockRecords: {
      name: 'GetListBlockRecords',
      I: GetListBlockRecordsRequest,
      O: GetListBlockRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetListItemRecords
     */
    getListItemRecords: {
      name: 'GetListItemRecords',
      I: GetListItemRecordsRequest,
      O: GetListItemRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetListRecords
     */
    getListRecords: {
      name: 'GetListRecords',
      I: GetListRecordsRequest,
      O: GetListRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetPostRecords
     */
    getPostRecords: {
      name: 'GetPostRecords',
      I: GetPostRecordsRequest,
      O: GetPostRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetProfileRecords
     */
    getProfileRecords: {
      name: 'GetProfileRecords',
      I: GetProfileRecordsRequest,
      O: GetProfileRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetActorChatDeclarationRecords
     */
    getActorChatDeclarationRecords: {
      name: 'GetActorChatDeclarationRecords',
      I: GetActorChatDeclarationRecordsRequest,
      O: GetActorChatDeclarationRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetNotificationDeclarationRecords
     */
    getNotificationDeclarationRecords: {
      name: 'GetNotificationDeclarationRecords',
      I: GetNotificationDeclarationRecordsRequest,
      O: GetNotificationDeclarationRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetStatusRecords
     */
    getStatusRecords: {
      name: 'GetStatusRecords',
      I: GetStatusRecordsRequest,
      O: GetStatusRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetRepostRecords
     */
    getRepostRecords: {
      name: 'GetRepostRecords',
      I: GetRepostRecordsRequest,
      O: GetRepostRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetThreadGateRecords
     */
    getThreadGateRecords: {
      name: 'GetThreadGateRecords',
      I: GetThreadGateRecordsRequest,
      O: GetThreadGateRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetPostgateRecords
     */
    getPostgateRecords: {
      name: 'GetPostgateRecords',
      I: GetPostgateRecordsRequest,
      O: GetPostgateRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetLabelerRecords
     */
    getLabelerRecords: {
      name: 'GetLabelerRecords',
      I: GetLabelerRecordsRequest,
      O: GetLabelerRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetStarterPackRecords
     */
    getStarterPackRecords: {
      name: 'GetStarterPackRecords',
      I: GetStarterPackRecordsRequest,
      O: GetStarterPackRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Follows
     *
     * @generated from rpc gndr.Service.GetActorFollowsActors
     */
    getActorFollowsActors: {
      name: 'GetActorFollowsActors',
      I: GetActorFollowsActorsRequest,
      O: GetActorFollowsActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetFollowers
     */
    getFollowers: {
      name: 'GetFollowers',
      I: GetFollowersRequest,
      O: GetFollowersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetFollows
     */
    getFollows: {
      name: 'GetFollows',
      I: GetFollowsRequest,
      O: GetFollowsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Verifications
     *
     * @generated from rpc gndr.Service.GetVerificationRecords
     */
    getVerificationRecords: {
      name: 'GetVerificationRecords',
      I: GetVerificationRecordsRequest,
      O: GetVerificationRecordsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetVerificationsIssued
     */
    getVerificationsIssued: {
      name: 'GetVerificationsIssued',
      I: GetVerificationsIssuedRequest,
      O: GetVerificationsIssuedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetVerificationsReceived
     */
    getVerificationsReceived: {
      name: 'GetVerificationsReceived',
      I: GetVerificationsReceivedRequest,
      O: GetVerificationsReceivedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Likes
     *
     * @generated from rpc gndr.Service.GetLikesBySubject
     */
    getLikesBySubject: {
      name: 'GetLikesBySubject',
      I: GetLikesBySubjectRequest,
      O: GetLikesBySubjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetLikesBySubjectSorted
     */
    getLikesBySubjectSorted: {
      name: 'GetLikesBySubjectSorted',
      I: GetLikesBySubjectSortedRequest,
      O: GetLikesBySubjectSortedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetLikesByActorAndSubjects
     */
    getLikesByActorAndSubjects: {
      name: 'GetLikesByActorAndSubjects',
      I: GetLikesByActorAndSubjectsRequest,
      O: GetLikesByActorAndSubjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetActorLikes
     */
    getActorLikes: {
      name: 'GetActorLikes',
      I: GetActorLikesRequest,
      O: GetActorLikesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reposts
     *
     * @generated from rpc gndr.Service.GetRepostsBySubject
     */
    getRepostsBySubject: {
      name: 'GetRepostsBySubject',
      I: GetRepostsBySubjectRequest,
      O: GetRepostsBySubjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetRepostsByActorAndSubjects
     */
    getRepostsByActorAndSubjects: {
      name: 'GetRepostsByActorAndSubjects',
      I: GetRepostsByActorAndSubjectsRequest,
      O: GetRepostsByActorAndSubjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetActorReposts
     */
    getActorReposts: {
      name: 'GetActorReposts',
      I: GetActorRepostsRequest,
      O: GetActorRepostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Quotes
     *
     * @generated from rpc gndr.Service.GetQuotesBySubjectSorted
     */
    getQuotesBySubjectSorted: {
      name: 'GetQuotesBySubjectSorted',
      I: GetQuotesBySubjectSortedRequest,
      O: GetQuotesBySubjectSortedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Interaction Counts
     *
     * @generated from rpc gndr.Service.GetInteractionCounts
     */
    getInteractionCounts: {
      name: 'GetInteractionCounts',
      I: GetInteractionCountsRequest,
      O: GetInteractionCountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetCountsForUsers
     */
    getCountsForUsers: {
      name: 'GetCountsForUsers',
      I: GetCountsForUsersRequest,
      O: GetCountsForUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetStarterPackCounts
     */
    getStarterPackCounts: {
      name: 'GetStarterPackCounts',
      I: GetStarterPackCountsRequest,
      O: GetStarterPackCountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetListCounts
     */
    getListCounts: {
      name: 'GetListCounts',
      I: GetListCountsRequest,
      O: GetListCountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetNewUserCountForRange
     */
    getNewUserCountForRange: {
      name: 'GetNewUserCountForRange',
      I: GetNewUserCountForRangeRequest,
      O: GetNewUserCountForRangeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Profile
     *
     * @generated from rpc gndr.Service.GetActors
     */
    getActors: {
      name: 'GetActors',
      I: GetActorsRequest,
      O: GetActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetDidsByHandles
     */
    getDidsByHandles: {
      name: 'GetDidsByHandles',
      I: GetDidsByHandlesRequest,
      O: GetDidsByHandlesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Relationships
     *
     * @generated from rpc gndr.Service.GetRelationships
     */
    getRelationships: {
      name: 'GetRelationships',
      I: GetRelationshipsRequest,
      O: GetRelationshipsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetBlockExistence
     */
    getBlockExistence: {
      name: 'GetBlockExistence',
      I: GetBlockExistenceRequest,
      O: GetBlockExistenceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists
     *
     * @generated from rpc gndr.Service.GetActorLists
     */
    getActorLists: {
      name: 'GetActorLists',
      I: GetActorListsRequest,
      O: GetActorListsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetListMembers
     */
    getListMembers: {
      name: 'GetListMembers',
      I: GetListMembersRequest,
      O: GetListMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetListMembership
     */
    getListMembership: {
      name: 'GetListMembership',
      I: GetListMembershipRequest,
      O: GetListMembershipResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetListCount
     */
    getListCount: {
      name: 'GetListCount',
      I: GetListCountRequest,
      O: GetListCountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Mutes
     *
     * @generated from rpc gndr.Service.GetActorMutesActor
     */
    getActorMutesActor: {
      name: 'GetActorMutesActor',
      I: GetActorMutesActorRequest,
      O: GetActorMutesActorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetMutes
     */
    getMutes: {
      name: 'GetMutes',
      I: GetMutesRequest,
      O: GetMutesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Mutelists
     *
     * @generated from rpc gndr.Service.GetActorMutesActorViaList
     */
    getActorMutesActorViaList: {
      name: 'GetActorMutesActorViaList',
      I: GetActorMutesActorViaListRequest,
      O: GetActorMutesActorViaListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetMutelistSubscription
     */
    getMutelistSubscription: {
      name: 'GetMutelistSubscription',
      I: GetMutelistSubscriptionRequest,
      O: GetMutelistSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetMutelistSubscriptions
     */
    getMutelistSubscriptions: {
      name: 'GetMutelistSubscriptions',
      I: GetMutelistSubscriptionsRequest,
      O: GetMutelistSubscriptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Thread Mutes
     *
     * @generated from rpc gndr.Service.GetThreadMutesOnSubjects
     */
    getThreadMutesOnSubjects: {
      name: 'GetThreadMutesOnSubjects',
      I: GetThreadMutesOnSubjectsRequest,
      O: GetThreadMutesOnSubjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Blocks
     *
     * @generated from rpc gndr.Service.GetBidirectionalBlock
     */
    getBidirectionalBlock: {
      name: 'GetBidirectionalBlock',
      I: GetBidirectionalBlockRequest,
      O: GetBidirectionalBlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetBlocks
     */
    getBlocks: {
      name: 'GetBlocks',
      I: GetBlocksRequest,
      O: GetBlocksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Blocklists
     *
     * @generated from rpc gndr.Service.GetBidirectionalBlockViaList
     */
    getBidirectionalBlockViaList: {
      name: 'GetBidirectionalBlockViaList',
      I: GetBidirectionalBlockViaListRequest,
      O: GetBidirectionalBlockViaListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetBlocklistSubscription
     */
    getBlocklistSubscription: {
      name: 'GetBlocklistSubscription',
      I: GetBlocklistSubscriptionRequest,
      O: GetBlocklistSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetBlocklistSubscriptions
     */
    getBlocklistSubscriptions: {
      name: 'GetBlocklistSubscriptions',
      I: GetBlocklistSubscriptionsRequest,
      O: GetBlocklistSubscriptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Notifications
     *
     * @generated from rpc gndr.Service.GetNotificationPreferences
     */
    getNotificationPreferences: {
      name: 'GetNotificationPreferences',
      I: GetNotificationPreferencesRequest,
      O: GetNotificationPreferencesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetNotifications
     */
    getNotifications: {
      name: 'GetNotifications',
      I: GetNotificationsRequest,
      O: GetNotificationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetNotificationSeen
     */
    getNotificationSeen: {
      name: 'GetNotificationSeen',
      I: GetNotificationSeenRequest,
      O: GetNotificationSeenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetUnreadNotificationCount
     */
    getUnreadNotificationCount: {
      name: 'GetUnreadNotificationCount',
      I: GetUnreadNotificationCountRequest,
      O: GetUnreadNotificationCountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetActivitySubscriptionDids
     */
    getActivitySubscriptionDids: {
      name: 'GetActivitySubscriptionDids',
      I: GetActivitySubscriptionDidsRequest,
      O: GetActivitySubscriptionDidsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetActivitySubscriptionsByActorAndSubjects
     */
    getActivitySubscriptionsByActorAndSubjects: {
      name: 'GetActivitySubscriptionsByActorAndSubjects',
      I: GetActivitySubscriptionsByActorAndSubjectsRequest,
      O: GetActivitySubscriptionsByActorAndSubjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.UpdateNotificationSeen
     */
    updateNotificationSeen: {
      name: 'UpdateNotificationSeen',
      I: UpdateNotificationSeenRequest,
      O: UpdateNotificationSeenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * FeedGenerators
     *
     * @generated from rpc gndr.Service.GetActorFeeds
     */
    getActorFeeds: {
      name: 'GetActorFeeds',
      I: GetActorFeedsRequest,
      O: GetActorFeedsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetSuggestedFeeds
     */
    getSuggestedFeeds: {
      name: 'GetSuggestedFeeds',
      I: GetSuggestedFeedsRequest,
      O: GetSuggestedFeedsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetFeedGeneratorStatus
     */
    getFeedGeneratorStatus: {
      name: 'GetFeedGeneratorStatus',
      I: GetFeedGeneratorStatusRequest,
      O: GetFeedGeneratorStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.SearchFeedGenerators
     */
    searchFeedGenerators: {
      name: 'SearchFeedGenerators',
      I: SearchFeedGeneratorsRequest,
      O: SearchFeedGeneratorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Feeds
     *
     * @generated from rpc gndr.Service.GetAuthorFeed
     */
    getAuthorFeed: {
      name: 'GetAuthorFeed',
      I: GetAuthorFeedRequest,
      O: GetAuthorFeedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetTimeline
     */
    getTimeline: {
      name: 'GetTimeline',
      I: GetTimelineRequest,
      O: GetTimelineResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetListFeed
     */
    getListFeed: {
      name: 'GetListFeed',
      I: GetListFeedRequest,
      O: GetListFeedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Threads
     *
     * @generated from rpc gndr.Service.GetThread
     */
    getThread: {
      name: 'GetThread',
      I: GetThreadRequest,
      O: GetThreadResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Search
     *
     * @generated from rpc gndr.Service.SearchActors
     */
    searchActors: {
      name: 'SearchActors',
      I: SearchActorsRequest,
      O: SearchActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.SearchPosts
     */
    searchPosts: {
      name: 'SearchPosts',
      I: SearchPostsRequest,
      O: SearchPostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.SearchStarterPacks
     */
    searchStarterPacks: {
      name: 'SearchStarterPacks',
      I: SearchStarterPacksRequest,
      O: SearchStarterPacksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Suggestions
     *
     * @generated from rpc gndr.Service.GetFollowSuggestions
     */
    getFollowSuggestions: {
      name: 'GetFollowSuggestions',
      I: GetFollowSuggestionsRequest,
      O: GetFollowSuggestionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetSuggestedEntities
     */
    getSuggestedEntities: {
      name: 'GetSuggestedEntities',
      I: GetSuggestedEntitiesRequest,
      O: GetSuggestedEntitiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Labels
     *
     * @generated from rpc gndr.Service.GetLabels
     */
    getLabels: {
      name: 'GetLabels',
      I: GetLabelsRequest,
      O: GetLabelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetAllLabelers
     */
    getAllLabelers: {
      name: 'GetAllLabelers',
      I: GetAllLabelersRequest,
      O: GetAllLabelersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Starter packs
     *
     * @generated from rpc gndr.Service.GetActorStarterPacks
     */
    getActorStarterPacks: {
      name: 'GetActorStarterPacks',
      I: GetActorStarterPacksRequest,
      O: GetActorStarterPacksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sync
     *
     * @generated from rpc gndr.Service.GetLatestRev
     */
    getLatestRev: {
      name: 'GetLatestRev',
      I: GetLatestRevRequest,
      O: GetLatestRevResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Moderation
     *
     * @generated from rpc gndr.Service.GetBlobTakedown
     */
    getBlobTakedown: {
      name: 'GetBlobTakedown',
      I: GetBlobTakedownRequest,
      O: GetBlobTakedownResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetRecordTakedown
     */
    getRecordTakedown: {
      name: 'GetRecordTakedown',
      I: GetRecordTakedownRequest,
      O: GetRecordTakedownResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetActorTakedown
     */
    getActorTakedown: {
      name: 'GetActorTakedown',
      I: GetActorTakedownRequest,
      O: GetActorTakedownResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Identity
     *
     * @generated from rpc gndr.Service.GetIdentityByDid
     */
    getIdentityByDid: {
      name: 'GetIdentityByDid',
      I: GetIdentityByDidRequest,
      O: GetIdentityByDidResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.GetIdentityByHandle
     */
    getIdentityByHandle: {
      name: 'GetIdentityByHandle',
      I: GetIdentityByHandleRequest,
      O: GetIdentityByHandleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Graph
     *
     * @generated from rpc gndr.Service.GetFollowsFollowing
     */
    getFollowsFollowing: {
      name: 'GetFollowsFollowing',
      I: GetFollowsFollowingRequest,
      O: GetFollowsFollowingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Ping
     *
     * @generated from rpc gndr.Service.Ping
     */
    ping: {
      name: 'Ping',
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Moderation
     *
     * @generated from rpc gndr.Service.TakedownBlob
     */
    takedownBlob: {
      name: 'TakedownBlob',
      I: TakedownBlobRequest,
      O: TakedownBlobResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.TakedownRecord
     */
    takedownRecord: {
      name: 'TakedownRecord',
      I: TakedownRecordRequest,
      O: TakedownRecordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.TakedownActor
     */
    takedownActor: {
      name: 'TakedownActor',
      I: TakedownActorRequest,
      O: TakedownActorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.UpdateActorUpstreamStatus
     */
    updateActorUpstreamStatus: {
      name: 'UpdateActorUpstreamStatus',
      I: UpdateActorUpstreamStatusRequest,
      O: UpdateActorUpstreamStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.UntakedownBlob
     */
    untakedownBlob: {
      name: 'UntakedownBlob',
      I: UntakedownBlobRequest,
      O: UntakedownBlobResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.UntakedownRecord
     */
    untakedownRecord: {
      name: 'UntakedownRecord',
      I: UntakedownRecordRequest,
      O: UntakedownRecordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.UntakedownActor
     */
    untakedownActor: {
      name: 'UntakedownActor',
      I: UntakedownActorRequest,
      O: UntakedownActorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Ingestion
     *
     * @generated from rpc gndr.Service.CreateActorMute
     */
    createActorMute: {
      name: 'CreateActorMute',
      I: CreateActorMuteRequest,
      O: CreateActorMuteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.DeleteActorMute
     */
    deleteActorMute: {
      name: 'DeleteActorMute',
      I: DeleteActorMuteRequest,
      O: DeleteActorMuteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.ClearActorMutes
     */
    clearActorMutes: {
      name: 'ClearActorMutes',
      I: ClearActorMutesRequest,
      O: ClearActorMutesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.CreateActorMutelistSubscription
     */
    createActorMutelistSubscription: {
      name: 'CreateActorMutelistSubscription',
      I: CreateActorMutelistSubscriptionRequest,
      O: CreateActorMutelistSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.DeleteActorMutelistSubscription
     */
    deleteActorMutelistSubscription: {
      name: 'DeleteActorMutelistSubscription',
      I: DeleteActorMutelistSubscriptionRequest,
      O: DeleteActorMutelistSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.ClearActorMutelistSubscriptions
     */
    clearActorMutelistSubscriptions: {
      name: 'ClearActorMutelistSubscriptions',
      I: ClearActorMutelistSubscriptionsRequest,
      O: ClearActorMutelistSubscriptionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.CreateThreadMute
     */
    createThreadMute: {
      name: 'CreateThreadMute',
      I: CreateThreadMuteRequest,
      O: CreateThreadMuteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.DeleteThreadMute
     */
    deleteThreadMute: {
      name: 'DeleteThreadMute',
      I: DeleteThreadMuteRequest,
      O: DeleteThreadMuteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gndr.Service.ClearThreadMutes
     */
    clearThreadMutes: {
      name: 'ClearThreadMutes',
      I: ClearThreadMutesRequest,
      O: ClearThreadMutesResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
